/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** État de l'API et de la base */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Create Dataset */
        post: operations["create_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Dataset */
        patch: operations["patch_dataset_api_v1_datasets__dataset_id__patch"];
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lancer une exécution depuis l'URL de la source
         * @description Exécute le pipeline de bout en bout.
         *
         *     Le traitement est synchrone : un dataset de quelques mégaoctets se traite en
         *     quelques secondes, ce qui ne justifie pas d'introduire une file de tâches.
         */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lancer une exécution à partir d'un fichier envoyé */
        post: operations["create_run_from_upload_api_v1_runs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Results */
        get: operations["get_results_api_v1_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_v1_runs__run_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_api_v1_runs__run_id__comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rapport JSON complet, téléchargeable */
        get: operations["get_report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_datasets__dataset_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_run_from_upload_api_v1_runs_upload_post */
        Body_create_run_from_upload_api_v1_runs_upload_post: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /** File */
            file: string;
        };
        /** CheckDiff */
        CheckDiff: {
            /** Check Name */
            check_name: string;
            /** From */
            from: ("success" | "warning" | "failed" | "skipped") | null;
            /** To */
            to: ("success" | "warning" | "failed" | "skipped") | null;
        };
        /** DatasetCreate */
        DatasetCreate: {
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Expected Frequency
             * @default P1D
             * @example P1D
             * @example PT6H
             */
            expected_frequency: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Reference Schema */
            reference_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /** DatasetOut */
        DatasetOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Expected Frequency */
            expected_frequency: string;
            /** Active */
            active: boolean;
            source: components["schemas"]["SourceOut"];
            last_run?: components["schemas"]["LastRunSummary"] | null;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Reference Schema */
            reference_schema: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DatasetPatch */
        DatasetPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Expected Frequency
             * @example P1D
             * @example PT6H
             */
            expected_frequency?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /** Reference Schema */
            reference_schema?: {
                [key: string]: unknown;
            } | null;
            /** Active */
            active?: boolean | null;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Expected Frequency */
            expected_frequency: string;
            /** Active */
            active: boolean;
            source: components["schemas"]["SourceOut"];
            last_run?: components["schemas"]["LastRunSummary"] | null;
        };
        /** Freshness */
        Freshness: {
            /** Date */
            date: string | null;
            /** Origin */
            origin: string | null;
            /** Age Hours */
            age_hours: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LastRunSummary */
        LastRunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "warning" | "failed" | "skipped";
            /** Score */
            score: number | null;
        };
        /** Page[RunSummary] */
        Page_RunSummary_: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** QualityResultOut */
        QualityResultOut: {
            /** Check Name */
            check_name: string;
            /** Dimension */
            dimension: string;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "warning" | "failed" | "skipped";
            /** Weight */
            weight: number;
            /** Score */
            score: number;
            /** Failed Count */
            failed_count: number;
            /** Threshold */
            threshold: {
                [key: string]: unknown;
            };
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** RenamedColumn */
        RenamedColumn: {
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** RunComparisonOut */
        RunComparisonOut: {
            /**
             * Previous Run Id
             * Format: uuid
             */
            previous_run_id: string;
            /** Rows Delta */
            rows_delta: number | null;
            /** Rows Delta Pct */
            rows_delta_pct: number | null;
            /** Score Delta */
            score_delta: number | null;
            schema_diff: components["schemas"]["SchemaDiff"];
            /** Checks Diff */
            checks_diff: components["schemas"]["CheckDiff"][];
        };
        /** RunCreate */
        RunCreate: {
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
        };
        /** RunDetail */
        RunDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "warning" | "failed" | "skipped";
            /** Score */
            score: number | null;
            /** Rows Read */
            rows_read: number | null;
            /** Columns Read */
            columns_read: number | null;
            /** Error Message */
            error_message: string | null;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /** Checksum */
            checksum: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Results */
            results: components["schemas"]["QualityResultOut"][];
            /** Schema */
            schema: components["schemas"]["SchemaFieldOut"][];
            comparison: components["schemas"]["RunComparisonOut"] | null;
        };
        /** RunSummary */
        RunSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Dataset Id
             * Format: uuid
             */
            dataset_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "warning" | "failed" | "skipped";
            /** Score */
            score: number | null;
            /** Rows Read */
            rows_read: number | null;
            /** Columns Read */
            columns_read: number | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * SchemaDiff
         * @description Différences de schéma entre deux exécutions.
         *
         *     Décrit explicitement plutôt qu'en objet libre : c'est ce qui permet au
         *     dashboard d'être vérifié par le compilateur au lieu de deviner la forme.
         */
        SchemaDiff: {
            /** Added */
            added: string[];
            /** Removed */
            removed: string[];
            /** Renamed */
            renamed: components["schemas"]["RenamedColumn"][];
            /** Type Changed */
            type_changed: components["schemas"]["TypeChangedColumn"][];
        };
        /** SchemaFieldOut */
        SchemaFieldOut: {
            /** Column Name */
            column_name: string;
            /** Data Type */
            data_type: string;
            /** Nullable */
            nullable: boolean;
            /** Position */
            position: number;
        };
        /** SourceCreate */
        SourceCreate: {
            /**
             * Name
             * @example data.economie.gouv.fr
             */
            name: string;
            /**
             * Url
             * @example https://example.org/prix.csv
             */
            url?: string | null;
            /**
             * Format
             * @default csv
             */
            format: string;
            /**
             * License
             * @example Licence Ouverte / Open Licence 2.0
             */
            license?: string | null;
        };
        /** SourceOut */
        SourceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string | null;
            /** Format */
            format: string;
            /** License */
            license: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TypeChangedColumn */
        TypeChangedColumn: {
            /** Column */
            column: string;
            /** From */
            from: string;
            /** To */
            to: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"][];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    create_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_dataset_api_v1_datasets__dataset_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_from_upload_api_v1_runs_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_run_from_upload_api_v1_runs_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_results_api_v1_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_api_v1_runs__run_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaFieldOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_v1_runs__run_id__comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunComparisonOut"];
                };
            };
            /** @description Première exécution : rien à comparer */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_datasets__dataset_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RunSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
